{
 "title": "nDPId",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ndpid_db_name", "query": "${VAR_NDPID_DB_NAME}" }
  ]
 },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"events\"\n  )"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"events\"\n  )"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"events\" and\n    r._field != \"packet_flow_count\"\n  )"
    }
   ]
  },
  {
   "title": "Packet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"events\" and\n    (r._field == \"packet_count\" or\n     r._field == \"packet_flow_count\")\n  )"
    }
   ]
  },
  {
   "title": "Detection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"events\" and\n    (r._field == \"flow_detected_count\" or\n     r._field == \"flow_detection_update_count\" or\n     r._field == \"flow_guessed_count\")\n  )"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"events\"\n  )"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Data Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"general\" and\n    (r._field == \"flow_src_total_bytes\" or\n     r._field == \"flow_dst_total_bytes\" or\n     r._field == \"json_bytes\")\n  )"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"general\" and\n    (r._field == \"flow_src_total_bytes\" or\n     r._field == \"flow_dst_total_bytes\" or\n     r._field == \"json_bytes\")\n  )"
    }
   ]
  },
  {
   "title": "Bytes Transmitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"general\" and\n    r._field == \"flow_src_total_bytes\"\n  )"
    }
   ]
  },
  {
   "title": "JSON Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"general\" and\n    r._field == \"json_lines\"\n  )"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"general\" and\n    r._field == \"flow_dst_total_bytes\"\n  )"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"general\" and\n    (r._field == \"flow_src_total_bytes\" or\n     r._field == \"flow_dst_total_bytes\")\n  )"
    }
   ]
  },
  { "title": "Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Breed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"breed\"\n  )"
    },
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_active_count\")\n  )"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_active_count\")\n  )"
    }
   ]
  },
  {
   "title": "Detection",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_detected_count\" or\n     r._field == \"flow_guessed_count\" or\n     r._field == \"flow_not_detected_count\")\n  )"
    },
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_active_count\")\n  )"
    }
   ]
  },
  {
   "title": "Category",
   "type": "gauge",
   "gridPos": { "h": 27, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"category\"\n  )"
    },
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_active_count\")\n  )"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"state\"\n  )"
    },
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_active_count\")\n  )"
    }
   ]
  },
  {
   "title": "Confidence",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"confidence\"\n  )"
    },
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_active_count\")\n  )"
    }
   ]
  },
  {
   "title": "Total Risks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"risks\"\n  )"
    }
   ]
  },
  {
   "title": "Risk Severity",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"severity\"\n  )"
    },
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_active_count\")\n  )"
    }
   ]
  },
  { "title": "Risks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  { "gridPos": { "h": 24, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Risk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"risks\"\n  )"
    }
   ]
  },
  { "title": "Flow (Simplified / Historic)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Breed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"breed\"\n  )"
    }
   ]
  },
  {
   "title": "Detection",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"detection\" and\n    (r._field == \"flow_detected_count\" or\n     r._field == \"flow_guessed_count\" or\n     r._field == \"flow_not_detected_count\")\n  )"
    }
   ]
  },
  {
   "title": "Risk",
   "type": "state-timeline",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"risks\"\n  )"
    }
   ]
  },
  { "title": "Layer3 / Layer4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Layer3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"layer3\"\n  )"
    }
   ]
  },
  {
   "title": "Layer4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "query": "from(bucket: \"${ndpid_db_name}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"layer4\"\n  )"
    }
   ]
  }
 ]
}